version: '3.8'

services:
  pdf-converter:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8000
      - CONVERSION_TIMEOUT=60
      - MAX_WORKERS=4
      - MAX_FILE_SIZE=52428800
      - TEMP_DIR=/tmp
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
